FourthTeamProject/Models/PetHeavenModels/Employees.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class Employees
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public int WorkShift { get; set; }
        public int EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeRole { get; set; }

        public virtual WorkShift WorkShiftNavigation { get; set; }
    }
}

FourthTeamProject/Models/PetHeavenModels/HotelOrderDetail.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class HotelOrderDetail
    {
        public int HotelOrderDetailId { get; set; }
        public int? HotelOrderId { get; set; }
        public int? HotelId { get; set; }
        public DateTime? CheckIntime { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public int? OrderAmount { get; set; }
        public int? UnitPrice { get; set; }
        public bool? DetailStatus { get; set; }
        public string HotelName { get; set; }
        public string HotelCatagoryName { get; set; }

        public virtual HotelOrder HotelOrder { get; set; }
    }
}

FourthTeamProject/Models/PetHeavenModels/SalonOrderDetail.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonOrderDetail
    {
        public int SalonOrderDetailId { get; set; }
        public DateTime Appointment { get; set; }
        public bool DetailStatus { get; set; }
        public int UnitPrice { get; set; }
        public int SalonOrderId { get; set; }
        public string SalonCatagoryName { get; set; }
        public string SalonSolutionName { get; set; }
        public int SalonSolutionId { get; set; }

        public virtual SalonOrder SalonOrder { get; set; }
    }
}

FourthTeamProject/Models/ViewModel/HotelOrderDetailViewModel.cs
namespace FourthTeamProject.Models.ViewModel
{
    public class HotelOrderDetailViewModel
    {
        public int? HotelOrderId { get; set; }
        public int? HotelId { get; set; }
        public DateTime? CheckIntime { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public int? OrderAmount { get; set; }
        public int? UnitPrice { get; set; }
        public bool? DetailStatus { get; set; }
        public string HotelName { get; set; }
        public string HotelCatagoryName { get; set; }
    }
}

FourthTeamProject/Models/ViewModel/SalonOrderDetailViewModel.cs
namespace FourthTeamProject.Models.ViewModel
{
    public class SalonOrderDetailViewModel
    {
        public int SalonOrderDetailID { get; set; }
        public DateTime Appointment { get; set; }
        public bool DetailStatus { get; set; }
        public int UnitPrice { get; set; }
        public int SalonOrderID { get; set; }
        public int SalonSolutionID { get; set; }
        public string? SalonCatagoryName { get; set; }
        public string? SalonSolutionName { get; set; }
    }
}

FourthTeamProject/Controllers/EmployeesController.cs
using FourthTeamProject.Models.ViewModel;
using FourthTeamProject.PetHeavenModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace FourthTeamProject.Controllers
{


    public class EmployeesController : Controller
    {
        private readonly PetHeavenDbContext _db;


        public EmployeesController(PetHeavenDbContext context)
        {
            this._db = context;
        }


        public IActionResult EmployeeLogin()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> EmployeeLogin(EmployeeLoginViewModel model)
        {

            var user = _db.Employees.FirstOrDefault(x => x.EmployeeEmail == model.EmployeeEmail &&
             x.EmployeePassword == model.EmployeePassword);

            if (user == null)
            {
                ViewBag.Error = "帳號密碼錯誤";
                return View("EmployeeLogin");
            }


            var claims = new List<Claim>()
            {
                 new Claim(ClaimTypes.Name, user.EmployeeName),
               new Claim(ClaimTypes.Role, user.EmployeeRole),
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            await HttpContext.SignInAsync(claimsPrincipal);  //夾帶一個cookie出去
            return RedirectToAction("ProductCRUD", "ProductManage", new { area = "Admin" });
        }
        public async Task<IActionResult> EmployeeLogout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

FourthTeamProject/Controllers/ProductController.cs
using FourthTeamProject.PetHeavenModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Security.Claims;
using System.Text;
using System.Web;
using static FourthTeamProject.Models.ViewModel.CheckPageViewModel;

namespace FourthTeamProject.Controllers
{
	public class ProductController : Controller
	{
        private readonly PetHeavenDbContext _db;

	
		public IActionResult Index()
		{
			var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
			if (email != null)
			{
				ViewBag.Email = email;
			}
			return View();
		}

		public IActionResult Order() 
		{ 
			return View();
		}

        //金流
		public IActionResult Check()
		{
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            // 產生測試資訊
            ViewData["MerchantID"] = Config.GetSection("MerchantID").Value;//商店代號
            ViewData["MerchantOrderNo"] = DateTime.Now.ToString("yyyyMMddHHmmss");  //訂單編號
            ViewData["ExpireDate"] = DateTime.Now.AddDays(3).ToString("yyyyMMdd"); //繳費有效期限
            ViewData["ReturnURL"] = $"{Request.Scheme}://{Request.Host}/Product/OrderDone"; //支付完成返回商店網址
            //ViewData["CustomerURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}Home/CallbackCustomer"; //商店取號網址
            //ViewData["NotifyURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}Home/CallbackNotify"; //支付通知網址
            //ViewData["ClientBackURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}"; //返回商店網址
            
            var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
			if (email != null)
			{
                ViewBag.Email = email;
				return View();
			}
			return Redirect("/Member/Login");

		}

        /// <summary>
        /// 支付完成返回網址
        /// </summary>
        /// <returns></returns>
        public IActionResult OrderDone()
        {
            // 接收參數
            StringBuilder receive = new StringBuilder();
            foreach (var item in Request.Form)
            {
                receive.Append(item.Key + ":" + item.Value + ",");
            }
            ViewData["ReceiveObj"] = receive.ToString();
            
            // 解密訊息
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            string HashKey = Config.GetSection("HashKey").Value;//API 串接金鑰
            string HashIV = Config.GetSection("HashIV").Value;//API 串接密碼

            string TradeInfoDecrypt = DecryptAESHex(Request.Form["TradeInfo"], HashKey, HashIV);
            NameValueCollection decryptTradeCollection = HttpUtility.ParseQueryString(TradeInfoDecrypt);
            var tradeInfoObject = new Dictionary<string, string>();
            foreach (string key in decryptTradeCollection.AllKeys)
            {
                tradeInfoObject[key] = decryptTradeCollection[key];
            }
            string jsonString = JsonConvert.SerializeObject(tradeInfoObject);
            ViewBag.TradeInfo = jsonString;

            return View();
        }



        public IActionResult ProductDetail()
        {
            var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
            if (Request.Query.TryGetValue("Id", out var productId))
            {
				ViewBag.Email = email;
                ViewBag.productId = productId;
                return View();
            }
            return RedirectToAction("Index");
        }


        //金流方法
        /// <summary>
        /// 傳送訂單至藍新金流
        /// </summary>
        /// <param name="inModel"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        public IActionResult SendToNewebPay(SendToNewebPayIn inModel)
        {
            SendToNewebPayOut outModel = new SendToNewebPayOut();

            // 藍新金流線上付款

            //交易欄位
            List<KeyValuePair<string, string>> TradeInfo = new List<KeyValuePair<string, string>>();
            // 商店代號
            TradeInfo.Add(new KeyValuePair<string, string>("MerchantID", inModel.MerchantID));
            // 回傳格式
            TradeInfo.Add(new KeyValuePair<string, string>("RespondType", "String"));
            // TimeStamp
            TradeInfo.Add(new KeyValuePair<string, string>("TimeStamp", DateTimeOffset.Now.ToOffset(new TimeSpan(8, 0, 0)).ToUnixTimeSeconds().ToString()));
            // 串接程式版本
            TradeInfo.Add(new KeyValuePair<string, string>("Version", "2.0"));
            // 商店訂單編號
            TradeInfo.Add(new KeyValuePair<string, string>("MerchantOrderNo", inModel.MerchantOrderNo));
            // 訂單金額
            TradeInfo.Add(new KeyValuePair<string, string>("Amt", inModel.Amt));
            // 商品資訊
            TradeInfo.Add(new KeyValuePair<string, string>("ItemDesc", inModel.ItemDesc));
            // 繳費有效期限(適用於非即時交易)
            TradeInfo.Add(new KeyValuePair<string, string>("ExpireDate", inModel.ExpireDate));
            // 支付完成返回商店網址
            TradeInfo.Add(new KeyValuePair<string, string>("ReturnURL", inModel.ReturnURL));
            // 支付通知網址
            TradeInfo.Add(new KeyValuePair<string, string>("NotifyURL", inModel.NotifyURL));
            // 商店取號網址
            TradeInfo.Add(new KeyValuePair<string, string>("CustomerURL", inModel.CustomerURL));
            // 支付取消返回商店網址
            TradeInfo.Add(new KeyValuePair<string, string>("ClientBackURL", inModel.ClientBackURL));
            // 付款人電子信箱
            TradeInfo.Add(new KeyValuePair<string, string>("Email", inModel.Email));
            // 付款人電子信箱 是否開放修改(1=可修改 0=不可修改)
            TradeInfo.Add(new KeyValuePair<string, string>("EmailModify", "0"));

            TradeInfo.Add(new KeyValuePair<string, string>("CREDIT", "1"));

            TradeInfo.Add(new KeyValuePair<string, string>("VACC", "1"));

            string TradeInfoParam = string.Join("&", TradeInfo.Select(x => $"{x.Key}={x.Value}"));

            // API 傳送欄位
            // 商店代號
            outModel.MerchantID = inModel.MerchantID;
            // 串接程式版本
            outModel.Version = "2.0";
            //交易資料 AES 加解密
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            string HashKey = Config.GetSection("HashKey").Value;//API 串接金鑰
            string HashIV = Config.GetSection("HashIV").Value;//API 串接密碼
            string TradeInfoEncrypt = EncryptAESHex(TradeInfoParam, HashKey, HashIV);
            outModel.TradeInfo = TradeInfoEncrypt;
            //交易資料 SHA256 加密
            outModel.TradeSha = EncryptSHA256($"HashKey={HashKey}&{TradeInfoEncrypt}&HashIV={HashIV}");

            return Json(outModel);
        }

        /// <summary>
        /// 加密後再轉 16 進制字串
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>加密後的字串</returns>
        public string EncryptAESHex(string source, string cryptoKey, string cryptoIV)
        {
            string result = string.Empty;

            if (!string.IsNullOrEmpty(source))
            {
                var encryptValue = EncryptAES(Encoding.UTF8.GetBytes(source), cryptoKey, cryptoIV);

                if (encryptValue != null)
                {
                    result = BitConverter.ToString(encryptValue)?.Replace("-", string.Empty)?.ToLower();
                }
            }

            return result;
        }

        /// <summary>
        /// 字串加密AES
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>加密後字串</returns>
        public byte[] EncryptAES(byte[] source, string cryptoKey, string cryptoIV)
        {
            byte[] dataKey = Encoding.UTF8.GetBytes(cryptoKey);
            byte[] dataIV = Encoding.UTF8.GetBytes(cryptoIV);

            using (var aes = System.Security.Cryptography.Aes.Create())
            {
                aes.Mode = System.Security.Cryptography.CipherMode.CBC;
                aes.Padding = System.Security.Cryptography.PaddingMode.PKCS7;
                aes.Key = dataKey;
                aes.IV = dataIV;

                using (var encryptor = aes.CreateEncryptor())
                {
                    return encryptor.TransformFinalBlock(source, 0, source.Length);
                }
            }
        }

        /// <summary>
        /// 字串加密SHA256
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <returns>加密後字串</returns>
        public string EncryptSHA256(string source)
        {
            string result = string.Empty;

            using (System.Security.Cryptography.SHA256 algorithm = System.Security.Cryptography.SHA256.Create())
            {
                var hash = algorithm.ComputeHash(Encoding.UTF8.GetBytes(source));

                if (hash != null)
                {
                    result = BitConverter.ToString(hash)?.Replace("-", string.Empty)?.ToUpper();
                }

            }
            return result;
        }

        /// <summary>
        /// 16 進制字串解密
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>解密後的字串</returns>
        public string DecryptAESHex(string source, string cryptoKey, string cryptoIV)
        {
            string result = string.Empty;

            if (!string.IsNullOrEmpty(source))
            {
                // 將 16 進制字串 轉為 byte[] 後
                byte[] sourceBytes = ToByteArray(source);

                if (sourceBytes != null)
                {
                    // 使用金鑰解密後，轉回 加密前 value
                    result = Encoding.UTF8.GetString(DecryptAES(sourceBytes, cryptoKey, cryptoIV)).Trim();
                }
            }

FourthTeamProject/Views/Employees/AccessDenied.cshtml
<h1>請回到首頁登入後再重試</h1>

FourthTeamProject/Views/Employees/Create.cshtml
@model FourthTeamProject.PetHeavenModels.Product
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Product</h4>
<hr />

<div class="row">
    <div class="col-md-6 offset-md-3">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ProductTypeId" class="control-label">商品類別</label>
                        <select asp-for="ProductTypeId" class="form-control" asp-items="ViewBag.ProductTypeId"></select>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProductName" class="control-label">商品名稱</label>
                        <input asp-for="ProductName" class="form-control" />
                        <span asp-validation-for="ProductName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProductCatagoryId" class="control-label">商品分類</label>
                        <select asp-for="ProductCatagoryId" class="form-control" asp-items="ViewBag.ProductCatagoryId"></select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="UnitPrice" class="control-label">單價</label>
                        <input asp-for="UnitPrice" class="form-control" />
                        <span asp-validation-for="UnitPrice" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Stock" class="control-label">庫存</label>
                        <input asp-for="Stock" class="form-control" />
                        <span asp-validation-for="Stock" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="ProductStatus" class="control-label">商品狀態</label>
                        <select asp-for="ProductStatus" class="form-control">
                            <option value="true">上架</option>
                            <option value="false">下架</option>
                        </select>
                    </div>


                </div>
            </div>

            <div class="form-group">
                <label asp-for="ProductSpecification" class="control-label">商品規格</label>
                <input asp-for="ProductSpecification" class="form-control" />
                <span asp-validation-for="ProductSpecification" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductContent" class="control-label">商品內容</label>
                <input asp-for="ProductContent" class="form-control" />
                <span asp-validation-for="ProductContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>上傳圖片</label>
                <input type="file" name="mypic" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-primary" asp-area="Admin" asp-controller="Employees" asp-action="Productmanagement">返回列表</a>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#File1').change(function () {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imgPreview').attr('src', e.target.result);
            }
            reader.readAsDataURL(this.files[0]);
        });
    });
</script>

FourthTeamProject/Views/Employees/Productmanagement.cshtml
@model IEnumerable<FourthTeamProject.PetHeavenModels.Product>
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=device-width,initial-scale=1.0" />
    <meta name="format-detection" content="telephone=no, email=no, date=no, address=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <link href="~/css/ProductStyle/css/bksystem.css" rel="stylesheet" type="text/css" />
    <link href="~/css/ProductStyle/font/iconfont.css" rel="stylesheet" type="text/css" />
    <link href="~/css/ProductStyle/css/module.css" rel="stylesheet" type="text/css" />
    <link href="~/css/ProductStyle/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="~/css/SalonCSS/style.css" rel="stylesheet" />
    <title>商品管理</title>
    <script src="~/css/ProductStyle/js/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="~/css/ProductStyle/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/css/ProductStyle/js/HUpages.js" type="text/javascript"></script>
    <script src="~/css/ProductStyle/js/common.js" type="text/javascript"></script>
</head>

<body id="situation" style="height:100%  overflow-y:auto">
    <div class="pages-style">
    
        <div class="bk-con-menu " id="bk-con-menu">
        
       
            <div class="breadcrumb" id="breadcrumb">
                <ul class="clearfix menu-section menulist" id="menu-section">
                </ul>
            </div>
        </div>
    
        <div class="bk-con-message message-section" id="iframe_box">
       

           
            <div class="" style="margin-left:250px;" >
                <table class="gallery table table_list table_striped table-bordered" style="border:solid 1px;height:100%" id="">
                    <thead>
                        <a asp-area="Admin" asp-controller="Employees" asp-action="Create"  class="btn  btn-primary">新增商品</a>
                        <tr style="border:solid 1px">
                            <th>商品名稱</th>
                            <th>商品規格</th>
                            <th>商品內容</th>
                            <th>單價</th>
                            <th>庫存</th>
                            <th>商品狀態</th>
                            <th>商品分類</th>
                            <th>商品類型</th>
                            <th>商品圖片</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                                <td>@Html.DisplayFor(modelItem => item.ProductSpecification)</td>
                                <td>@Html.DisplayFor(modelItem => item.ProductContent)</td>
                                <td>@Html.DisplayFor(modelItem => item.UnitPrice)</td>
                                <td>@Html.DisplayFor(modelItem => item.Stock)</td>
                                <td>
                                    @if (item.ProductStatus)
                                    {
                                        <span>上架中</span>
                                    }
                                    else
                                    {
                                        <span>下架中</span>
                                    }
                                </td>
                                <td>@Html.DisplayFor(modelItem => item.ProductCatagory.ProductCatagoryName)</td>
                                <td>@Html.DisplayFor(modelItem => item.ProductType.ProductTypeName)</td>
                                <td>
                                    <partial name="_ShowPhotoPartial" model="@item" />
                                </td>
                                <td>
                                    <a asp-area="Admin" asp-controller="Employees" asp-action="Edit" asp-route-id="@item.ProductId" class="btn btn-primary">編輯</a>
                                    <a asp-area="Admin" asp-controller="Employees" asp-action="Details" asp-route-id="@item.ProductId" class="btn  btn-primary">明細</a>
                                    <a asp-area="Admin" asp-controller="Employees" asp-action="Delete" asp-route-id="@item.ProductId" class="btn  btn-primary">刪除</a>
                                 
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    function confirmBatchDelete() {
      
        var selectedIds = $(".product-checkbox:checked").map(function () {
            return $(this).val();
        }).get();

        if (selectedIds.length === 0) {
            alert("請選擇至少一個商品來刪除。");
            return;
        }

    
        if (confirm("確定要刪除選中的商品嗎？")) {
          
            $("#batchDeleteForm").submit();
        }
    }

    $(function () {
        $(document).ready(function () {
         
            $("#SelectAll").click(function () {
                
                var isChecked = $(this).prop("checked");

             
                $(".product-checkbox").prop("checked", isChecked);
            });
        });

        $("#situation").Hupage({
            slide: '#breadcrumb',
            padding: 15,
            menuModule: '#bk-con-menu',
            pagecontent: '.page_content',
            operation: '.operation',
            scrollbar: function (e) {
                e.niceScroll({
                    cursorcolor: "#dddddd",
                    cursoropacitymax: 1,
                    touchbehavior: false,
                    cursorwidth: "3px",
                    cursorborder: "0",
                    cursorborderradius: "3px",
                });
            },
            expand: function (thisBox, settings) {
                var pc = "";
                $(settings.pagecontent).css("margin-bottom") != null ? pc = parseInt($(settings.pagecontent).css("margin-bottom").replace("px", "")) : '';
                $(settings.pagecontent).css({ height: $(window).height() - $(settings.operation).outerHeight() - pc - (settings.padding * 2) })
                settings.scrollbar($(settings.slide) && $(settings.pagecontent));
            }
        });
    });


    $(document).ready(function () {
       
        $("#btnBatchDelete").click(function () {
          
            var selectedIds = $(".product-checkbox:checked").map(function () {
                return $(this).val();
            }).get();

            if (selectedIds.length === 0) {
                alert("請選擇至少一個商品來刪除。");
                return;
            }

            
            $.ajax({
                url: '@Url.Action("BatchDelete", "Product")',
                type: 'POST',
                data: JSON.stringify(selectedIds),
                contentType: 'application/json',
                success: function (result) {
                    if (result.success) {
                       
                        location.reload();
                    } else {
                       
                        alert(result.message);
                    }
                },
                error: function () {
                    alert("伺服器連線錯誤！");
                }
            });
        });
    });
  


    $(".upload-image").change(function () {
        var productId = $(this).data("product-id");
        var formData = new FormData();
        var files = $(this).get(0).files;

    
        for (var i = 0; i < files.length; i++) {
            formData.append("file", files[i]);
        }

       
        $.ajax({
            url: "@Url.Action("UploadImage", "productId")".replace("&#123;id&#125;", productId),
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
            success: function (result) {
                if (result.success) {
                 
                    var imageUrl = result.imageUrl;

               
                    $("#img_" + productId).attr("src", imageUrl);

                    alert("圖片上傳成功！");
                } else {
                    alert("圖片上傳失敗！");
                }
            },
            error: function () {
                alert("伺服器連線錯誤！");
            }
        });
    });
</script>

FourthTeamProject/Views/Employees/_ShowPhotoPartial.cshtml
@model FourthTeamProject.PetHeavenModels.Product

@if (Model.ProductImage != null)
{
    <img src="@Url.Action("ShowPhoto", "Product",
    new {id=Model.ProductId})"
         style="width:320px;height:240px"
         title="@Model.ProductName" />
}
else
{
    <img src="@Url.Content("~/images/NoImage.png")" style="width:320px;height:240px" />
}