FourthTeamProject/Models/PetHeavenModels/HotelOrderDetail.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class HotelOrderDetail
    {
        public int HotelOrderDetailId { get; set; }
        public int? HotelOrderId { get; set; }
        public int? HotelId { get; set; }
        public DateTime? CheckIntime { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public int? OrderAmount { get; set; }
        public int? UnitPrice { get; set; }
        public bool? DetailStatus { get; set; }
        public string HotelName { get; set; }
        public string HotelCatagoryName { get; set; }

        public virtual HotelOrder HotelOrder { get; set; }
    }
}

FourthTeamProject/Models/PetHeavenModels/SalonOrderDetail.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonOrderDetail
    {
        public int SalonOrderDetailId { get; set; }
        public DateTime Appointment { get; set; }
        public bool DetailStatus { get; set; }
        public int UnitPrice { get; set; }
        public int SalonOrderId { get; set; }
        public string SalonCatagoryName { get; set; }
        public string SalonSolutionName { get; set; }
        public int SalonSolutionId { get; set; }

        public virtual SalonOrder SalonOrder { get; set; }
    }
}

FourthTeamProject/Models/ViewModel/HotelOrderDetailViewModel.cs
namespace FourthTeamProject.Models.ViewModel
{
    public class HotelOrderDetailViewModel
    {
        public int? HotelOrderId { get; set; }
        public int? HotelId { get; set; }
        public DateTime? CheckIntime { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public int? OrderAmount { get; set; }
        public int? UnitPrice { get; set; }
        public bool? DetailStatus { get; set; }
        public string HotelName { get; set; }
        public string HotelCatagoryName { get; set; }
    }
}

FourthTeamProject/Models/ViewModel/SalonOrderDetailViewModel.cs
namespace FourthTeamProject.Models.ViewModel
{
    public class SalonOrderDetailViewModel
    {
        public int SalonOrderDetailID { get; set; }
        public DateTime Appointment { get; set; }
        public bool DetailStatus { get; set; }
        public int UnitPrice { get; set; }
        public int SalonOrderID { get; set; }
        public int SalonSolutionID { get; set; }
        public string? SalonCatagoryName { get; set; }
        public string? SalonSolutionName { get; set; }
    }
}

FourthTeamProject/Areas/Admin/Controllers/EmployeesManageController.cs
using FourthTeamProject.Models.ViewModel;
using FourthTeamProject.PetHeavenModels;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;

namespace FourthTeamProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class EmployeesManageController : Controller
    {
        private readonly PetHeavenDbContext _db;


        public EmployeesManageController(PetHeavenDbContext context)
        {
            this._db = context;
        }


        //[Authorize(Roles = "admin")]

        public async Task<IActionResult> Ordermanagement(string search, int page = 1)
        {
            int pageSize = 10;
            IQueryable<ProductOrder> query = _db.ProductOrder
                .Include(p => p.Payment)
                .Include(p => p.Invoice)
                .Include(p => p.Member)
                .Include(p => p.ProductOrderDetail);

            if (!string.IsNullOrEmpty(search))
            {
                if (search.StartsWith("/"))
                {
                    string birthdate = search.Substring(1); // get rid of the leading '/'
                    query = query.Where(order => order.Member.MemberBirthday.ToString().Contains(birthdate));
                }
                else
                {
                    query = query.Where(order => order.MemberId.ToString().Contains(search)
                                                  || order.OrderMemberName.Contains(search));
                }
            }
            var totalRecords = await query.CountAsync();
            var totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            query = query.Skip((page - 1) * pageSize).Take(pageSize);

            var orders = await query.ToListAsync();

            var viewModel = new ProductOrderViewModel
            {
                Orders = orders,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View("~/Areas/Admin/Views/EmployeesManage/Ordermanagement.cshtml", viewModel);
            

        }




        public async Task<IActionResult> OrderDetail(int id)
        {
            var productOrderDetails = await _db.ProductOrderDetail.Where(detail => detail.OrderId == id).ToListAsync();

            if (productOrderDetails == null || productOrderDetails.Count == 0)
            {
                return NotFound();
            }

            return View("~/Areas/Admin/Views/EmployeesManage/OrderDetail.cshtml", productOrderDetails);
        }



        public async Task<IActionResult> SalonOrdermanagement(string search, int page = 1)
        {
            int pageSize = 10;
            IQueryable<SalonOrder> query = _db.SalonOrder
                .Include(p => p.Payment)
                .Include(p => p.Invoice)
                .Include(p => p.Member)
                .Include(p => p.SalonOrderDetail);

            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(order => order.MemberId.ToString().Contains(search)
                                            || order.OrderMemberName.Contains(search));
            }

            var totalRecords = await query.CountAsync();
            var totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            query = query.Skip((page - 1) * pageSize).Take(pageSize);

            var orders = await query.ToListAsync();

            var viewModel = new SalonOrderViewModel
            {
                Orders = orders,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View(viewModel);
        }



        public async Task<IActionResult> SalonOrderDetail(int id)
        {
            var SalonOrderDetails = await _db.SalonOrderDetail.Where(detail => detail.SalonOrderId == id).ToListAsync();

            if (SalonOrderDetails == null || SalonOrderDetails.Count == 0)
            {
                return NotFound();
            }

            return View("~/Areas/Admin/Views/EmployeesManage/SalonOrderDetail.cshtml", SalonOrderDetails);
        }
        public async Task<IActionResult> HotelOrdermanagement(string search, int page = 1)
        {
            int pageSize = 10;
            IQueryable<HotelOrder> query = _db.HotelOrder
                .Include(p => p.Payment)
                .Include(p => p.Invoice)
                .Include(p => p.Member)
                .Include(p => p.HotelOrderDetail);

            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(order => order.MemberId.ToString().Contains(search)
                                            || order.Member.MemberName.Contains(search));
            }

            var totalRecords = await query.CountAsync();
            var totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            query = query.Skip((page - 1) * pageSize).Take(pageSize);

            var orders = await query.ToListAsync();

            var viewModel = new HotelOrderPageViewModel
            {
                Orders = orders,
                CurrentPage = page,
                TotalPages = totalPages
            };

            return View(viewModel);
        }



        public async Task<IActionResult> HotelOrderDetail(int id)
        {
            var HotelOrderDetails = await _db.HotelOrderDetail.Where(detail => detail.HotelOrderId == id).ToListAsync();

            if (HotelOrderDetails == null || HotelOrderDetails.Count == 0)
            {
                return NotFound();
            }

            return View("~/Areas/Admin/Views/EmployeesManage/HotelOrderDetail.cshtml", HotelOrderDetails);
        }


        public async Task<IActionResult> EmployeeLogout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        public async Task<IActionResult> MemberDetailsPartial(int memberId)
        {
            var member = await _db.Member.FindAsync(memberId);

            if (member == null)
            {
                return NotFound();
            }

            return PartialView("_MemberDetailsPartial", member);
        }




    }

}

FourthTeamProject/Areas/Admin/Views/EmployeesManage/HotelOrderDetail.cshtml
@model IEnumerable<FourthTeamProject.PetHeavenModels.HotelOrderDetail>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">
    <link id="theme-style" rel="stylesheet" href="~/css/System/css/portal.css">
</head>
<body class="app">
    <div class="app-wrapper">
        <div class="app-content pt-3 p-md-3 p-lg-4">
            <div class="container-xl">
                <div class="row g-3 mb-4 align-items-center justify-content-between">
                    <div class="col-auto">
                        <h1 class="app-page-title mb-0">訂單管理系統-旅館</h1>
                    </div>
                    <div class="col-auto">
                        <div class="page-utilities">
                            <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                                <div class="col-auto">
                                    <form class="app-search-form" asp-area="Admin" asp-controller="EmployeesManage" asp-action="HotelOrdermanagement" method="get">
                                        <input type="text" placeholder="Search..." name="search" class="form-control search-input">
                                        <button type="submit" class="btn search-btn btn-primary"><i class="fas fa-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-content" id="orders-table-tab-content">
                    <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
                        <div class="app-card app-card-orders-table shadow-sm mb-5">
                            <div class="app-card-body">
                                <div class="table-responsive">
                                    <table class="table app-table-hover mb-0 text-left">
                                        <thead>
                                            <tr>
                                                <th class="cell">訂單編號</th>
                                                <th class="cell">訂單明細編號</th>
                                                <th class="cell">旅館編號</th>
                                                <th class="cell">單價</th>
                                                <th class="cell">旅館種類</th>
                                                <th class="cell">旅館名稱</th>
                                                <th class="cell">入住時間</th>
                                                <th class="cell">退房時間</th>
                                                <th class="cell">天數</th>


                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(modelItem => item.HotelOrderId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.HotelOrderDetailId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.HotelId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.UnitPrice)</td>

                                                    <td>@Html.DisplayFor(modelItem => item.HotelCatagoryName)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.HotelName)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.CheckIntime)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.CheckOutTime)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.OrderAmount)天</td>


                                                </tr>
                                            }
                                        <td colspan="7">總金額：@Model.Sum(item => item.UnitPrice * item.OrderAmount)</td>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <nav class="app-pagination">
                            <ul class="pagination justify-content-center">
                                <li class="page-item disabled">
                                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">Next</a>
                                </li>
                            </ul>
                        </nav><!--//app-pagination-->

                    </div>
                </div>
            </div>
        </div>

        <footer class="app-footer">
            <div class="container text-center py-3">
            </div>
        </footer>

    </div>
    <script src="~/css/System/assets/plugins/popper.min.js"></script>
    <script src="~/css/System/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/css/System/assets/js/app.js"></script>
    <script defer src="~/css/System/plugins/fontawesome/js/all.min.js"></script>

</body>
</html>

FourthTeamProject/Areas/Admin/Views/EmployeesManage/HotelOrdermanagement.cshtml
@model FourthTeamProject.Models.ViewModel.HotelOrderPageViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">
    <link id="theme-style" rel="stylesheet" href="~/css/System/css/portal.css">
</head>
<body class="app">
    <div class="app-wrapper">
        <div class="app-content pt-3 p-md-3 p-lg-4">
            <div class="container-xl">
                <div class="row g-3 mb-4 align-items-center justify-content-between">
                    <div class="col-auto">
                        <h1 class="app-page-title mb-0">訂單管理系統-旅館</h1>
                    </div>
                    <div class="col-auto">
                        <div class="page-utilities">
                            <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                                <div class="col-auto">
                                    <form class="app-search-form" asp-area="Admin" asp-controller="EmployeesManage" asp-action="HotelOrdermanagement" method="get">
                                        <input type="text" placeholder="Search..." name="search" class="form-control search-input">
                                        <button type="submit" class="btn search-btn btn-primary"><i class="fas fa-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-content" id="orders-table-tab-content">
                    <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
                        <div class="app-card app-card-orders-table shadow-sm mb-5">
                            <div class="app-card-body">
                                <div class="table-responsive">
                                    <table class="table app-table-hover mb-0 text-left">
                                        <thead>
                                            <tr>
                                                <th class="cell">訂單編號</th>
                                                <th class="cell">會員編號</th>
                                                <th class="cell">客戶名稱</th>
                                                <th class="cell">訂單日期</th>
                                                <th class="cell">訂單狀態</th>
                                                <th class="cell">總計</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.Orders)
                                            {
                                                <tr>
                                                    <td class="cell">@Html.DisplayFor(modelItem=>item.HoyelOrderId)</td>
                                                    <td class="cell">@Html.DisplayFor(modelItem=>item.MemberId)</td>
                                                    <td class="cell">@Html.DisplayFor(modelItem=>item.Member.MemberName)</td>
                                                    <td class="cell">@Html.DisplayFor(modelItem=>item.HotelOrderDate)<span class="truncate"></span></td>
                                                    <td class="cell">
                                                        @if (item.OrderStatus)
                                                        {
                                                            <span class="badge bg-success">@Html.DisplayFor(modelItem=>item.OrderStatus)已付款</span>
                                                        }
                                                        else
                                                        {
                                                            <span class="badge bg-danger">@Html.DisplayFor(modelItem=>item.OrderStatus)未付款</span>
                                                        }
                                                    </td>
                                                    <td class="cell" style="list-style-type:arabic-indic"><a asp-area="Admin" asp-controller="EmployeesManage" asp-route-id="@item.HoyelOrderId" asp-action="HotelOrderDetail">View</a></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <nav class="app-pagination">
                            <ul class="pagination justify-content-center">
                                <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                                    <a class="page-link" asp-controller="EmployeesManage" asp-action="HotelOrdermanagement" asp-route-page="@(Model.CurrentPage - 1)">Previous</a>
                                </li>
                                @for (int i = 1; i <= Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                        <a class="page-link" asp-controller="EmployeesManage" asp-action="HotelOrdermanagement" asp-route-page="@i">@i</a>
                                    </li>
                                }
                                <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                                    <a class="page-link" asp-controller="EmployeesManage" asp-action="HotelOrdermanagement" asp-route-page="@(Model.CurrentPage + 1)">Next</a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                </div>
            </div>
        </div>

        <footer class="app-footer">
            <div class="container text-center py-3">
            </div>
        </footer>

    </div>
    <script src="~/css/System/assets/plugins/popper.min.js"></script>
    <script src="~/css/System/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/css/System/assets/js/app.js"></script>
    <script defer src="~/css/System/plugins/fontawesome/js/all.min.js"></script>

</body>
</html>

FourthTeamProject/Areas/Admin/Views/EmployeesManage/SalonOrderDetail.cshtml
@model IEnumerable<FourthTeamProject.PetHeavenModels.SalonOrderDetail>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="favicon.ico">
    <link id="theme-style" rel="stylesheet" href="~/css/System/css/portal.css">
</head>
<body class="app">
    <div class="app-wrapper">
        <div class="app-content pt-3 p-md-3 p-lg-4">
            <div class="container-xl">
                <div class="row g-3 mb-4 align-items-center justify-content-between">
                    <div class="col-auto">
                        <h1 class="app-page-title mb-0">訂單管理系統-美容</h1>
                    </div>
                    <div class="col-auto">
                        <div class="page-utilities">
                            <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                                <div class="col-auto">
                                    <form class="app-search-form" asp-area="Admin" asp-controller="EmployeesManage" asp-action="SalonOrdermanagement" method="get">
                                        <input type="text" placeholder="Search..." name="search" class="form-control search-input">
                                        <button type="submit" class="btn search-btn btn-primary"><i class="fas fa-search"></i></button>
                                    </form>
                                </div>

                                <div class="col-auto">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-content" id="orders-table-tab-content">
                    <div class="tab-pane fade show active" id="orders-all" role="tabpanel" aria-labelledby="orders-all-tab">
                        <div class="app-card app-card-orders-table shadow-sm mb-5">
                            <div class="app-card-body">
                                <div class="table-responsive">
                                    <table class="table app-table-hover mb-0 text-left">
                                        <thead>
                                            <tr>
                                                <th class="cell">訂單編號</th>
                                                <th class="cell">訂單明細編號</th>
                                                <th class="cell">商品編號</th>
                                                <th class="cell">單價</th>
                                                <th class="cell">美容項目名稱</th>
                                                <th class="cell">美容種類</th>


                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(modelItem => item.SalonOrderId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.SalonOrderDetailId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.SalonSolutionId)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.UnitPrice)</td>

                                                    <td>@Html.DisplayFor(modelItem => item.SalonSolutionName)</td>
                                                    <td>@Html.DisplayFor(modelItem => item.SalonCatagoryName)</td>


                                                </tr>
                                            }
                                        <td colspan="7">總金額：@Model.Sum(item => item.UnitPrice * 1)</td>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <nav class="app-pagination">
                            <ul class="pagination justify-content-center">
                                <li class="page-item disabled">
                                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">Next</a>
                                </li>
                            </ul>
                        </nav><!--//app-pagination-->

                    </div>
                </div>
            </div>
        </div>

        <footer class="app-footer">
            <div class="container text-center py-3">
            </div>
        </footer>

    </div>
    <script src="~/css/System/assets/plugins/popper.min.js"></script>
    <script src="~/css/System/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/css/System/assets/js/app.js"></script>
    <script defer src="~/css/System/plugins/fontawesome/js/all.min.js"></script>

</body>
</html>