FourthTeamProject/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Net.Mail;
using System.Text;
using System.Net;
using System.Text.Json;
using FourthTeamProject.Services;
using FourthTeamProject.PetHeavenModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.Data.SqlClient;
using System.Security.Principal;
using FourthTeamProject.Models.ViewModel;
using FourthTeamProject.Models.PetHeavenModels;

namespace FourthTeamProject.Controllers
{
    public class MemberController : Controller
    {
        private readonly PetHeavenDbContext _db;
        private readonly EncryptService encrypt;

        public MemberController(PetHeavenDbContext context, EncryptService encrypt)
        {
            _db = context;
            this.encrypt = encrypt;
        }

        //public MemberController(PetHeavenDbContext context)
        //{
        //    this._db = context;
        //}
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            var user = _db.Member.FirstOrDefault(x => x.MemberAccount == model.c_MemberAccount &&
             x.MemberPassword == model.c_MemberPassword);

            if (user != null)
            {
                ViewBag.Error = "帳號已經存在!!";
                return View("Member/Login");
            }

            _db.Member.Add(new Member()
            {
                MemberAccount = model.c_MemberAccount,
                MemberPassword = model.c_MemberPassword,
                MemberAddress = model.c_MemberAddress,

                MemberEmail = model.c_MemberEmail,
                MemberGender = model.c_MemberGender,
                MemberName = model.c_MemberName,
                MemberPhone = model.c_MemberPhone,
                MemberIsActive = model.c_MemberIsActive


            });
            _db.SaveChanges();
            //寄信
            var obj = new AesValidationDto(model.c_MemberAccount, DateTime.Now.AddDays(3));
            var jString = JsonSerializer.Serialize(obj);
            var code = encrypt.AesEncryptToBase64(jString);


            var mail = new MailMessage()
            {
                From = new MailAddress("mstyle912012@gmail.com"),
                Subject = "啟用網站驗證",
                Body = (@$"請點這<a href='https://localhost:7089/Home/Index?code= {code}'>這裡</a>來啟用你的帳號"),
                IsBodyHtml = true,
                BodyEncoding = Encoding.UTF8,
            };
            mail.To.Add(new MailAddress(model.c_MemberEmail));

            try
            {
                using (var sm = new SmtpClient("smtp.gmail.com", 587)) //465 ssl
                {
                    sm.EnableSsl = true;
                    sm.Credentials = new NetworkCredential("mystyle912012@gmail.com", "zkghpbiqhsviyrus");
                    sm.Send(mail);
                }
            }
            catch (Exception ex)
            {
                //ViewBag.Error = "邮件发送失败：" + ex.Message;
                throw;

            }
            return View();
        }


        public async Task<IActionResult> Enable(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return BadRequest("Invalid code");
            }

            var str = encrypt.AesDecryptToString(code);

            if (string.IsNullOrEmpty(str))
            {
                return BadRequest($"{code}");
            }

            var obj = JsonSerializer.Deserialize<AesValidationDto>(str);
            if (DateTime.Now > obj.ExpiredDate)
            {
                return BadRequest("Code has expired");
            }

            var user = _db.Member.FirstOrDefault(x => x.MemberAccount == obj.CMemberAccount);
            if (user != null)
            {
                user.MemberIsActive = true;
                _db.SaveChanges();
            }

            return Ok(new { code, str });
        }


        [HttpPost]
        public async Task<IActionResult> Login(MemberLoginViewModel model)
        {
            var user = _db.Member.FirstOrDefault(x => x.MemberAccount == model.MemberAccount &&
             x.MemberPassword == model.MemberPassword);

            if (user == null)
            {
                ViewBag.Error = "帳號密碼錯誤";
                return View("Login");


            }

            var claims = new List<Claim>()
            {
            new Claim(ClaimTypes.Name, user.MemberName),
            new Claim(ClaimTypes.Email, user.MemberEmail),

             };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
            await HttpContext.SignInAsync(claimsPrincipal);  //夾帶一個cookie出去
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult ForgetPassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Forgetpassword(ForgetpasswordViewModel model)
        {
            var user = _db.Member.FirstOrDefault(x => x.MemberEmail == model.MemberEmail);

            if (user == null)
            {
                ViewBag.Error = "帳號已經存在!!";
                return View("Login");
            }
            //寄信
            var obj = new AesValidationDto(model.MemberEmail, DateTime.Now.AddDays(3));
            var jString = JsonSerializer.Serialize(obj);
            var code = encrypt.AesEncryptToBase64(jString);


            var mail = new MailMessage()
            {
                From = new MailAddress("mstyle912012@gmail.com"),
                Subject = "忘記密碼",
                Body = (@$"請點這<a href='https://localhost:7089/Home/Index?code= {code}'>這裡</a>來啟用你的帳號"),
                IsBodyHtml = true,
                BodyEncoding = Encoding.UTF8,
            };
            mail.To.Add(new MailAddress(model.MemberEmail));

            try
            {
                using (var sm = new SmtpClient("smtp.gmail.com", 587)) //465 ssl
                {
                    sm.EnableSsl = true;
                    sm.Credentials = new NetworkCredential("mystyle912012@gmail.com", "zkghpbiqhsviyrus");
                    sm.Send(mail);
                }
            }
            catch (Exception ex)
            {
                //ViewBag.Error = "邮件发送失败：" + ex.Message;
                throw;

            }
            return View();
        }
        public IActionResult Reset()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Reset(ForgetpasswordViewModel model)
        {
            var user = _db.Member.FirstOrDefault(x => x.MemberEmail == model.MemberEmail);
            if (user == null)
            {

                return NotFound();
            }
            user.MemberPassword = model.NewPassword;
            try
            {
                _db.SaveChanges();
                return View("Login");
            }
            catch (Exception ex)
            {

                return StatusCode(500, "密碼更新失敗：" + ex.Message);
            }

        }
    }
}

FourthTeamProject/Controllers/ProductController.cs
using FourthTeamProject.PetHeavenModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Security.Claims;
using System.Text;
using System.Web;
using static FourthTeamProject.Models.ViewModel.CheckPageViewModel;

namespace FourthTeamProject.Controllers
{
	public class ProductController : Controller
	{
        private readonly PetHeavenDbContext _db;

	
		public IActionResult Index()
		{
			var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
			if (email != null)
			{
				ViewBag.Email = email;
			}
			return View();
		}

		public IActionResult Order() 
		{ 
			return View();
		}

        //金流
		public IActionResult Check()
		{
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            // 產生測試資訊
            ViewData["MerchantID"] = Config.GetSection("MerchantID").Value;//商店代號
            ViewData["MerchantOrderNo"] = DateTime.Now.ToString("yyyyMMddHHmmss");  //訂單編號
            ViewData["ExpireDate"] = DateTime.Now.AddDays(3).ToString("yyyyMMdd"); //繳費有效期限
            ViewData["ReturnURL"] = $"{Request.Scheme}://{Request.Host}/Product/OrderDone"; //支付完成返回商店網址
            //ViewData["CustomerURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}Home/CallbackCustomer"; //商店取號網址
            //ViewData["NotifyURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}Home/CallbackNotify"; //支付通知網址
            //ViewData["ClientBackURL"] = $"{Request.Scheme}://{Request.Host}{Request.Path}"; //返回商店網址
            
            var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
			if (email != null)
			{
                ViewBag.Email = email;
				return View();
			}
			return Redirect("/Member/Login");

		}

        /// <summary>
        /// 支付完成返回網址
        /// </summary>
        /// <returns></returns>
        public IActionResult OrderDone()
        {
            // 接收參數
            StringBuilder receive = new StringBuilder();
            foreach (var item in Request.Form)
            {
                receive.Append(item.Key + ":" + item.Value + ",");
            }
            ViewData["ReceiveObj"] = receive.ToString();
            
            // 解密訊息
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            string HashKey = Config.GetSection("HashKey").Value;//API 串接金鑰
            string HashIV = Config.GetSection("HashIV").Value;//API 串接密碼

            string TradeInfoDecrypt = DecryptAESHex(Request.Form["TradeInfo"], HashKey, HashIV);
            NameValueCollection decryptTradeCollection = HttpUtility.ParseQueryString(TradeInfoDecrypt);
            var tradeInfoObject = new Dictionary<string, string>();
            foreach (string key in decryptTradeCollection.AllKeys)
            {
                tradeInfoObject[key] = decryptTradeCollection[key];
            }
            string jsonString = JsonConvert.SerializeObject(tradeInfoObject);
            ViewBag.TradeInfo = jsonString;

            return View();
        }



        public IActionResult ProductDetail()
        {
            var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email)?.Value;
            if (Request.Query.TryGetValue("Id", out var productId))
            {
				ViewBag.Email = email;
                ViewBag.productId = productId;
                return View();
            }
            return RedirectToAction("Index");
        }


        //金流方法
        /// <summary>
        /// 傳送訂單至藍新金流
        /// </summary>
        /// <param name="inModel"></param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        public IActionResult SendToNewebPay(SendToNewebPayIn inModel)
        {
            SendToNewebPayOut outModel = new SendToNewebPayOut();

            // 藍新金流線上付款

            //交易欄位
            List<KeyValuePair<string, string>> TradeInfo = new List<KeyValuePair<string, string>>();
            // 商店代號
            TradeInfo.Add(new KeyValuePair<string, string>("MerchantID", inModel.MerchantID));
            // 回傳格式
            TradeInfo.Add(new KeyValuePair<string, string>("RespondType", "String"));
            // TimeStamp
            TradeInfo.Add(new KeyValuePair<string, string>("TimeStamp", DateTimeOffset.Now.ToOffset(new TimeSpan(8, 0, 0)).ToUnixTimeSeconds().ToString()));
            // 串接程式版本
            TradeInfo.Add(new KeyValuePair<string, string>("Version", "2.0"));
            // 商店訂單編號
            TradeInfo.Add(new KeyValuePair<string, string>("MerchantOrderNo", inModel.MerchantOrderNo));
            // 訂單金額
            TradeInfo.Add(new KeyValuePair<string, string>("Amt", inModel.Amt));
            // 商品資訊
            TradeInfo.Add(new KeyValuePair<string, string>("ItemDesc", inModel.ItemDesc));
            // 繳費有效期限(適用於非即時交易)
            TradeInfo.Add(new KeyValuePair<string, string>("ExpireDate", inModel.ExpireDate));
            // 支付完成返回商店網址
            TradeInfo.Add(new KeyValuePair<string, string>("ReturnURL", inModel.ReturnURL));
            // 支付通知網址
            TradeInfo.Add(new KeyValuePair<string, string>("NotifyURL", inModel.NotifyURL));
            // 商店取號網址
            TradeInfo.Add(new KeyValuePair<string, string>("CustomerURL", inModel.CustomerURL));
            // 支付取消返回商店網址
            TradeInfo.Add(new KeyValuePair<string, string>("ClientBackURL", inModel.ClientBackURL));
            // 付款人電子信箱
            TradeInfo.Add(new KeyValuePair<string, string>("Email", inModel.Email));
            // 付款人電子信箱 是否開放修改(1=可修改 0=不可修改)
            TradeInfo.Add(new KeyValuePair<string, string>("EmailModify", "0"));

            TradeInfo.Add(new KeyValuePair<string, string>("CREDIT", "1"));

            TradeInfo.Add(new KeyValuePair<string, string>("VACC", "1"));

            string TradeInfoParam = string.Join("&", TradeInfo.Select(x => $"{x.Key}={x.Value}"));

            // API 傳送欄位
            // 商店代號
            outModel.MerchantID = inModel.MerchantID;
            // 串接程式版本
            outModel.Version = "2.0";
            //交易資料 AES 加解密
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            string HashKey = Config.GetSection("HashKey").Value;//API 串接金鑰
            string HashIV = Config.GetSection("HashIV").Value;//API 串接密碼
            string TradeInfoEncrypt = EncryptAESHex(TradeInfoParam, HashKey, HashIV);
            outModel.TradeInfo = TradeInfoEncrypt;
            //交易資料 SHA256 加密
            outModel.TradeSha = EncryptSHA256($"HashKey={HashKey}&{TradeInfoEncrypt}&HashIV={HashIV}");

            return Json(outModel);
        }

        /// <summary>
        /// 加密後再轉 16 進制字串
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>加密後的字串</returns>
        public string EncryptAESHex(string source, string cryptoKey, string cryptoIV)
        {
            string result = string.Empty;

            if (!string.IsNullOrEmpty(source))
            {
                var encryptValue = EncryptAES(Encoding.UTF8.GetBytes(source), cryptoKey, cryptoIV);

                if (encryptValue != null)
                {
                    result = BitConverter.ToString(encryptValue)?.Replace("-", string.Empty)?.ToLower();
                }
            }

            return result;
        }

        /// <summary>
        /// 字串加密AES
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>加密後字串</returns>
        public byte[] EncryptAES(byte[] source, string cryptoKey, string cryptoIV)
        {
            byte[] dataKey = Encoding.UTF8.GetBytes(cryptoKey);
            byte[] dataIV = Encoding.UTF8.GetBytes(cryptoIV);

            using (var aes = System.Security.Cryptography.Aes.Create())
            {
                aes.Mode = System.Security.Cryptography.CipherMode.CBC;
                aes.Padding = System.Security.Cryptography.PaddingMode.PKCS7;
                aes.Key = dataKey;
                aes.IV = dataIV;

                using (var encryptor = aes.CreateEncryptor())
                {
                    return encryptor.TransformFinalBlock(source, 0, source.Length);
                }
            }
        }

        /// <summary>
        /// 字串加密SHA256
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <returns>加密後字串</returns>
        public string EncryptSHA256(string source)
        {
            string result = string.Empty;

            using (System.Security.Cryptography.SHA256 algorithm = System.Security.Cryptography.SHA256.Create())
            {
                var hash = algorithm.ComputeHash(Encoding.UTF8.GetBytes(source));

                if (hash != null)
                {
                    result = BitConverter.ToString(hash)?.Replace("-", string.Empty)?.ToUpper();
                }

            }
            return result;
        }

        /// <summary>
        /// 16 進制字串解密
        /// </summary>
        /// <param name="source">加密前字串</param>
        /// <param name="cryptoKey">加密金鑰</param>
        /// <param name="cryptoIV">cryptoIV</param>
        /// <returns>解密後的字串</returns>
        public string DecryptAESHex(string source, string cryptoKey, string cryptoIV)
        {
            string result = string.Empty;

            if (!string.IsNullOrEmpty(source))
            {
                // 將 16 進制字串 轉為 byte[] 後
                byte[] sourceBytes = ToByteArray(source);

                if (sourceBytes != null)
                {
                    // 使用金鑰解密後，轉回 加密前 value
                    result = Encoding.UTF8.GetString(DecryptAES(sourceBytes, cryptoKey, cryptoIV)).Trim();
                }
            }

FourthTeamProject/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="~/images/petsdaily.ico">
	
    <meta name="description" content="" />
    <meta name="keywords" content="" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Source+Serif+Pro:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/daterangepicker.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/style.css">

    <style>
        #top {
            margin-top: 81px;
        }

        #goToTop:hover {
            background-color: white;
            color: #1A374D;
            cursor: url('images/寵物商城pics/paw.png'), auto;
        }

        #goToTop {
            position: fixed;
            bottom: 20px;
            right: 20px;
            width: 50px;
            height: 50px;
            background-color: #1A374D;
            color: #fff;
            border-radius: 50%;
            text-align: center;
            line-height: 50px;
            border: none;
            outline: none;
            cursor: pointer;
        }

        #header .site-nav {
            min-height: 81px
        }
    </style>
    <title>寵物 · 日安｜Pets Daily</title>

    @await RenderSectionAsync("Styles", required: false)
</head>

<body>

    <header id="header">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close">
                    <span class="icofont-close js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <nav class="site-nav">
            <div class="container">
                <div class="site-navigation">
                    <a asp-controller="Home" asp-action="Index" class="logo m-0">PETS DAILY<span class="text-primary">.</span></a>

                    <ul class="js-clone-nav d-none d-lg-inline-block text-left site-menu float-right">
                        <li class="active"><a asp-controller="Home" asp-action="Index">首頁</a></li>
                        <li><a asp-controller="Product" asp-action="Index">寵物商城</a></li>
                        <li><a asp-controller="PetHotel" asp-action="Index">寵物旅館</a></li>   
                        <li><a asp-controller="PetSalon" asp-action="SalonIndex">寵物美容</a></li>
                        

                        @{
                            @if (User.Identity.IsAuthenticated && !User.IsInRole("admin"))
                            {
                                <li>
                                    <a asp-controller="Member" asp-action="Index">會員中心</a>
                                </li>
                                <a asp-controller="Employees" asp-action="EmployeeLogout">登出</a>
                            }
                            else
                            {
                                <li>
                                    <a asp-controller="Member" asp-action="Login">會員登入</a>
                                </li>
                            }
                        }


                        <li>
                    


                    </ul>

                    <a asp-controller="" asp-action="" class="burger ml-auto float-right site-menu-toggle js-menu-toggle d-inline-block d-lg-none light" data-toggle="collapse" data-target="#main-navbar">
                        <span></span>
                    </a>

                </div>
            </div>
        </nav>
    </header>
    <main>
        <div id="top">
            @RenderBody()
        </div>

    </main>

    <button id="goToTop">Top</button>

    <div class="site-footer">
        <div class="inner first">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-6">
                        <div class="widget">
                            <h3 class="heading">關於日安</h3>
                            <p>致力為毛孩們提供更好的生活品質，給予陪伴我們的他們最好的呵護。</p>
                            <p>◆ 此專題網頁僅為教育練習使用</p>
                        </div>

                    </div>

                    <div class="col-md-12 col-lg-6">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="widget">
                                    <h3 class="heading">Contact</h3>
                                    <ul class="list-unstyled quick-info links">
                                        <li class="email">thm101team04@gmail.com</li>
                                        <li class="phone">+886 987 654 321</li>
                                        <li class="address"><a href="https://goo.gl/maps/BpxiWM1wBejFiBH8A?coh=178573&entry=tt">寵物 · 日安—台北商業大學旗艦館</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="widget">
                                    <h3 class="heading">企業端</h3>
                                    <ul class="list-unstyled quick-info links">
                                        @{
                                            if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                                            {
                                              
                                                <li>
                                                    <a asp-area="Admin" asp-controller="ProductManage" asp-action="ProductCRUD">員工系統</a>
                                                </li>

                                              
                                            }
                                            else
                                            {
                                                <li>
                                                    <a asp-controller="Employees" asp-action="EmployeeLogin">企業登入</a>
                                                </li>

                                            }
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="inner dark">
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-8 mb-3 mb-md-0 mx-auto">
                        <p>
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script>.
                            All Rights Reserved. &mdash;
                            Designed with love by
                            <a href="https://untree.co" class="link-highlight">Untree.co</a>
                            <!-- License information: https://untree.co/license/ -->
                            Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.fancybox.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/daterangepicker.js"></script>

    <script src="~/js/custom.js"></script>
    <script src="~/js/typed.js"></script>
    <script>
        $(function () {
            var slides = $('.slides'),
                images = slides.find('img');

            images.each(function (i) {
                $(this).attr('data-id', i + 1);
            })

            var typed = new Typed('.typed-words', {
                strings: ["Hotel Rooms.", " Salon.", " Selections.", " Health Care."],
                typeSpeed: 80,
                backSpeed: 80,
                backDelay: 4000,
                startDelay: 1000,
                loop: true,
                showCursor: true,
                preStringTyped: (arrayPos, self) => {
                    arrayPos++;
                    console.log(arrayPos);
                    $('.slides img').removeClass('active');
                    $('.slides img[data-id="' + arrayPos + '"]').addClass('active');
                }

            });
        })

        document.addEventListener('DOMContentLoaded', function () {
            var goToTopButton = document.getElementById('goToTop');
            goToTopButton.addEventListener('click', function () {
                window.scrollTo({ top: 0, behavior: 'smooth' });
            });
        });
    </script>


    
    

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FourthTeamProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>*@